# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e891e36900345cac82a79286dc70fd59ffca0a4395bc0338d9022f11f0f17d3ab6e192875ea5a1e9b9452595f079540992feddd235a4683ae176d0c6ca8bc2

test:
  secret_key_base: b5ffc6a1996e404342716568e23e25835b8fb67f65fc78923cc4ccccbf5264529a57cdce54e2b904e3367452bec7a85a7e68404fe46d4c5deb559eb9cc2ac7c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
